@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([invalid format])
    :Shows invalid command format parse exception;
    else ([else])
    if () then ([else])
    :Note gets added to person;
    :save to storage;
    :Shows note add success string;
    else ([total notes is more than 1000 characters])
        :Shows word limit exceeded parse exception;
    endif
endif
stop
@enduml
